### ISSUE TITLE
Fatal Error when Rocksdb selected

### ISSUE THREAD

**Issue by fanaticalfishing** [fireduck64/jelectrum#20]
The Rocksdb performs its self tests fine.
But when I try to start jelectrum with the rocksdb selected, jelectrum crashes.
I tested it on two different machine, same error, Ubuntu 14.04
The error is pasted in the url below
http://pastebin.com/9y8PSJhH

**Comment by nomnombtc** [comment]
Hello,

I had a similar problem, after reading everything again multiple times I noticed a hint in
DATABASE.md, that if you have problems you should try rebuilding rocksdb library, that worked for me.
See here: https://github.com/fireduck64/jelectrum/blob/master/DATABASE.md#rocksdb

**Comment by fanaticalfishing** [comment]
Hi, Thank you.
Yes I saw that too. Rebuilding it didn't help.
The rocksdb runs file during its self tests. But when called by jelectrum it crashes.

Edit, I completely flushed all java from the system and reinstalled openjdk-7-jdk.
http://askubuntu.com/questions/84483/how-to-completely-uninstall-java
Then rebuilt rocks db and jelectrum
Now it works fine.
