### ISSUE TITLE
Add relayfee to protocol

### ISSUE THREAD

**Issue by bauerj** [fireduck64/jelectrum#22]
2.6.4 clients are using this feature already.

See spesmilo/electrum-server@bb2d1581bad5fb64cf50eced70d53e6d10e63d20

**Comment by fireduck64** [comment]
Can you remind me what the relay fee is?  Is it the minimum fee for this node to relay the transaction?

I have to figure out what to do in the not directly bitcoind attached case.

**Comment by bauerj** [comment]
To quote the [Bitcoin technical glossary](https://bitcoin.org/en/glossary/minimum-relay-fee):

> _Definition_ The minimum transaction fee a transaction must pay (if it isn’t a high-priority transaction) for a full node to relay that transaction to other nodes. There is no one minimum relay fee—each node chooses its own policy.

Does BitcoinJ have such a setting?

**Comment by bauerj** [comment]
If BitcoinJ relays all transactions no matter the fee it should be okay to just return 0 in that case.

**Comment by fireduck64** [comment]
Ok, cool.  I'll try to get this in this week.

**Comment by fireduck64** [comment]
Checked in now
