### ISSUE TITLE
using package manager

### ISSUE THREAD

**Issue by chpio** [fireduck64/jelectrum#23]
hoi

i think we should use a ~~package~~ dependency manager for managing the dependencies (that's the purpose of a dm :)). also it would fix the "rebuild rocksdb if your system is a bit different than mine" (and keep the git repository free of binary files, git sucks at managing bin files!). i know only of gradle and maven. is there a better alternative?

**Comment by fireduck64** [comment]
I agree in theory.  There are a few reasons I have not:

1) I don't know any and it would be a huge time sink for me to figure it out.
2) There are still a few weird things, like bitcoinj having some custom mods to not explode the memory.

I'm not concerned about gits efficiency with binary files, it might not be great, but it does fine.

Anyways, want to fork, setup on maven and then let me know so I can take a look?  I do think it would be a good improvement that I don't currently have time for.
