### ISSUE TITLE
use WeakReference in caches

### ISSUE THREAD

**Issue by chpio** [fireduck64/jelectrum#25]
https://docs.oracle.com/javase/7/docs/api/java/lang/ref/WeakReference.html

**Comment by chpio** [comment]
arg... it's SoftRef https://docs.oracle.com/javase/7/docs/api/java/lang/ref/SoftReference.html

**Comment by chpio** [comment]
i encountered a lot of OoM exceptions. so this would definitely help.

**Comment by chpio** [comment]
> electrum-server_1 | Exception in thread "Importer/RateThread/1-minute" Exception in thread "UtxoMgrThread" java.lang.OutOfMemoryError: Java heap space
> electrum-server_1 |     at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:64)
> electrum-server_1 |     at java.lang.StringBuilder.<init>(StringBuilder.java:85)
> electrum-server_1 |     at jelectrum.Importer$RateThread.run(Importer.java:716)
> electrum-server_1 | java.lang.OutOfMemoryError: Java heap space
> electrum-server_1 |     at java.util.LinkedList.linkLast(LinkedList.java:140)
> electrum-server_1 |     at java.util.LinkedList.add(LinkedList.java:336)
> electrum-server_1 |     at jelectrum.UtxoTrieNode.getHash(UtxoTrieNode.java:396)
> electrum-server_1 |     at jelectrum.UtxoTrieNode.getHash(UtxoTrieNode.java:414)
> electrum-server_1 |     at jelectrum.UtxoTrieMgr.getRootHash(UtxoTrieMgr.java:568)
> electrum-server_1 |     at jelectrum.UtxoTrieMgr$UtxoMgrThread.catchup(UtxoTrieMgr.java:936)
> electrum-server_1 |     at jelectrum.UtxoTrieMgr$UtxoMgrThread.run(UtxoTrieMgr.java:842)
> electrum-server_1 | Block 00000000000007bb446146fa4d42e373fd19b8754491a8fa2d512cc7e9791ad1 save failed.  Retrying
> electrum-server_1 | java.lang.OutOfMemoryError: Java heap space
> electrum-server_1 | #
> electrum-server_1 | # A fatal error has been detected by the Java Runtime Environment:
> electrum-server_1 | #
> electrum-server_1 | #  SIGSEGV (0xb) at pc=0x00007f286b670907, pid=1, tid=139809648506624
> electrum-server_1 | #
> electrum-server_1 | # JRE version: OpenJDK Runtime Environment (7.0_95) (build 1.7.0_95-b00)
> electrum-server_1 | # Java VM: OpenJDK 64-Bit Server VM (24.95-b01 mixed mode linux-amd64 compressed oops)
> electrum-server_1 | # Derivative: IcedTea 2.6.4
> electrum-server_1 | # Distribution: Debian GNU/Linux 8.2 (jessie), package 7u95-2.6.4-1~deb8u1
> electrum-server_1 | # Problematic frame:
> electrum-server_1 | # V  [libjvm.so+0x614907]

and a lot of these:

> electrum-server_1 | [error occurred during error reporting , id 0xb]

and then:

> [...]
> electrum-server_1 | [Too many errors, abort]
> electrum-server_1 | [Too many errors, abort]
> electrumserver_electrum-server_1 exited with code 139

sorry about this but i think i will start a rust implementation. i had a bad feeling after reading your code. the problem is that it would be my first rust project... so not professional either

**Comment by chpio** [comment]
> electrum-server_1 | 1-minute Block rate: 0.000/s   Transaction rate: 0.000/s     txq:0 blkq:8
> electrum-server_1 | {BLOCK_GET_ADDRESSES=1, BLOCK_WAIT_PREV=3, TX_QUEUE_WAIT=4}
> electrum-server_1 | Unable to get source transaction: e25c3dad00e5e66f4b7ca6d96e70490c591644ac9a1c6012e14b1d365e4bd725
> electrum-server_1 | Unable to get source transaction: e25c3dad00e5e66f4b7ca6d96e70490c591644ac9a1c6012e14b1d365e4bd725

and 800% cpu load (8 cores) looks like a spin lock... o.0 ?!

it crashed after a few mins. with an OoM:

> electrum-server_1 | Exception in thread "NioClientManager" java.lang.OutOfMemoryError: GC overhead limit exceeded

with `-Xmx12g`. (the first crash  was with `-Xmx6g`)

**Comment by fireduck64** [comment]
Have fun with a rust implementation.

You shouldn't get an OOM if you are running with at least 8gb of ram on the command line (with the -Xmx argument).

There is certainly room for improvement but I don't think having the cache data be cleaned up by the garbage collector is going to lead to a good time, a lot of it is pretty important for performance.

**Comment by chpio** [comment]
but it's only freed in the case of an OOM (or rather instead of the OOM).
