### ISSUE TITLE
Building error: build.xml does not exist

### ISSUE THREAD

**Issue by HashEngineering** [fireduck64/jelectrum#29]
The README.md says:

```
Build:
ant jar
```

But when I do the `ant jar` command, the following error is returned:

```
Buildfile: build.xml does not exist
Build failed
```

Additionally, there is BUILD file which appears to be for `bazel`.

Could you help me build this project?

**Comment by fireduck64** [comment]
Sorry, the docs are out of date.  It should build fine with bazel these
days.

**Comment by fireduck64** [comment]
I've updated the readme.  If there are any other questions, please let me know.

I am running jelectrum nodes on Bitcoin and Bitcoin Cash but I don't think anyone else is so I'm sure there are some rough edges.
