### ISSUE TITLE
Current master does not build anymore

### ISSUE THREAD

**Issue by gruve-p** [fireduck64/jelectrum#32]
Seems like `WORKSPACE` needs to be updated in order to build it

**Comment by fireduck64** [comment]
I'll take a look

**Comment by fireduck64** [comment]
What version of bazel are you running?
Bazel likes to change things and no longer work with newer versions.
The code currently seems to build fine with 4.2.2

**Comment by gruve-p** [comment]
> What version of bazel are you running? 

5.2.0 from https://releases.bazel.build/5.2.0/release/bazel-5.2.0-linux-x86_64 and https://github.com/bazelbuild/bazel/releases/tag/5.2.0

**Comment by fireduck64** [comment]
It works for me with 5.2-rc3.  I had to switch over to the testing track for the deb repo track to even get that.
I added a Dockerfile as a demo.

**Comment by gruve-p** [comment]
I will give it another try and reopen if I can't figure it out thanks

**Comment by fireduck64** [comment]
Works for me on bazel 4.2.2

However, bazel loves to break things on me.  Do you have a more recent one?

$ bazel version
Build label: 4.2.2
