### ISSUE TITLE
bitcoind peering on 8333 not clear

### ISSUE THREAD

**Issue by fireduck64** [fireduck64/jelectrum#5]
make configurable.  Make error on problems.

**Comment by SuBPaR42** [comment]
The local bitcoind mustn't be in listen=0 mode or else no block processing.  If the bitcoin.conf is using connect= versus addnode= that is synonymous with the option listen=0 and BitcoinJ cannot connect on localhost Port 8333 and therefore cannot process blocks and the leveldb (or DB of choice) will not generate.

**Comment by fireduck64** [comment]
Fixed with https://github.com/fireduck64/jelectrum/commit/1dcefce732cdab76a8669718cd7b8c6f54c183b9
